const Products = [{
    brandName: "ASOS DESIGN",
    colour: "",
    colourWayId: 60415840,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12315538,
    imageUrl: "http://images.asos-media.com/products/asos-design-wide-fit-oxford-shoes-in-tan-leather-with-toe-cap/12315538-1-tan",
    isSellingFast: false,
    name: "ASOS DESIGN tassel loafers in black faux suede",
    price: {current: {value: 36, text: "$36.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 36, text: "$36.00"},
    text: "$36.00"
  }, {
    brandName: "New Balance",
    colour: "",
    colourWayId: 60415840,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 11635845,
    imageUrl: "http://images.asos-media.com/products/new-balance-574-v2-pastel-mint-sneakers/11635845-1-mint",
    isSellingFast: false,
    name: "New Balance 574 V2 Pastel Mint Sneakers",
    price: {current: {value: 80, text: "$80.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 80, text: "$80.00"},
    text: "$80.00"
  }, {
    brandName: "ASOS DESIGN",
    colour: "",
    colourWayId: 60415840,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 66,
    imageUrl: "http://images.asos-media.com/products/asos-design-tassel-loafers-in-black-faux-suede/22665736-1-black",
    isSellingFast: false,
    name: "ASOS DESIGN tassel loafers in black faux suede",
    price: {current: {value: 36, text: "$36.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 36, text: "$36.00"},
    text: "$36.00"
  }, {
    brandName: "ASOS DESIGN",
    colour: "Black",
    colourWayId: 16409614,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12011431,
    imageUrl: "http://images.asos-media.com/products/asos-design-backless-mule-loafer-in-black-leather/12011431-1-black",
    isSellingFast: false,
    name: "ASOS DESIGN backless mule loafer in black leather",
    price: {current: {value: 56, text: "$56.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 56, text: "$56.00"},
    text: "$56.00"
}, {
    brandName: "Base London",
    colour: "Brown",
    colourWayId: 16424851,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12692372,
    imageUrl: "http://images.asos-media.com/products/base-london-hogan-lace-ups-in-brown/12692372-1-brown",
    isSellingFast: false,
    name: "Base London Hogan lace ups in brown",
    price: {current: {value: 119, text: "$119.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 119, text: "$119.00"},
    text: "$119.00"
  }, {
    brandName: "House of Hounds",
    colour: "Black",
    colourWayId: 16437086,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12718178,
    imageUrl: "http://images.asos-media.com/products/house-of-hounds-cooper-creepers-in-black-leather/12718178-1-black",
    isSellingFast: false,
    name: "House of Hounds cooper creepers in black leather",
    price: {current: {value: 125, text: "$125.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 125, text: "$125.00"},
    text: "$125.00"
  }, {
    brandName: "Nike Training",
    colour: "Black",
    colourWayId: 16443236,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12860967,
    imageUrl: "http://images.asos-media.com/products/nike-training-figertrap-sneakers-in-black/12860967-1-black",
    isSellingFast: false,
    name: "Nike Training Figertrap sneakers in black",
    price: {current: {value: 75, text: "$75.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 75, text: "$75.00"},
    text: "$75.00"
  }, {
    brandName: "Vans",
    colour: "Black",
    colourWayId: 16426527,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12907504,
    imageUrl: "http://images.asos-media.com/products/vans-varix-sneakers-in-black-color-block/12907504-1-black",
    isSellingFast: false,
    name: "Vans Varix sneakers in black color block",
    price: {current: {value: 100, text: "$100.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 100, text: "$100.00"},
    text: "$100.00"
  }, {
    brandName: "Vans",
    colour: "Black",
    colourWayId: 16426547,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12907695,
    imageUrl: "http://images.asos-media.com/products/vans-anaheim-sk8-hi-sneakers-in-leaf-print/12907695-1-black",
    isSellingFast: false,
    name: "Vans Anaheim Sk8-hi sneakers in leaf print",
    price: {current: {value: 90, text: "$90.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 90, text: "$90.00"},
    text: "$90.00"
  }, {
    brandName: "Vans",
    colour: "White",
    colourWayId: 16426553,
    groupId: null,
    hasMultiplePrices: false,
    hasVariantColours: false,
    id: 12907696,
    imageUrl: "http://images.asos-media.com/products/vans-anaheim-stripe-era-sneakers-in-red-blue/12907696-1-white",
    isSellingFast: false,
    name: "Vans Anaheim Stripe Era sneakers in red/blue",
    price: {current: {value: 80, text: "$80.00"}, previous: {value: null, text: ""}, rrp: {value: null, text: ""}},
    currency: "USD",
    current: {value: 80, text: "$80.00"},
    text: "$80.00"
  }
];

export default Products;